app/forms/ChangePassword.py
import sys
from flask_wtf import FlaskForm
from flask_login import current_user
from wtforms import PasswordField, SubmitField
from wtforms.validators import Required, EqualTo
from wtforms import ValidationError
from .. models.User import User

class ChangePassword(FlaskForm):
    existing_password = PasswordField("Existing Password", validators=[Required()])
    password = PasswordField("Password", validators=[Required(), 
                    EqualTo('confirm_password', 'Both passwords must match!')])
    confirm_password = PasswordField("Confirm Password", validators=[Required()])
    submit = SubmitField("Change Password")


    def validate_existing_password(self, field):
        user = User.query.filter_by(id=current_user.id).first()
        if not user.verify_password(field.data):
            raise ValidationError('Existing password is incorrect!')

app/forms/ForgotPasswordForm.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, ValidationError
from wtforms.validators import Required, Email
from .. models.User import User

class ForgotPasswordForm(FlaskForm):
    email = StringField("Email", validators=[Required(), Email()])
    submit = SubmitField("Submit")

    def validate_email(self, field):
        if field.name not in self.errors:
            if not User.query.filter_by(email=field.data).first():
                raise ValidationError('Email not registered with us!')

app/forms/LoginForm.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField
from wtforms.validators import Required, Email

class LoginForm(FlaskForm):
    email = StringField("Email", validators=[Required(), Email()])
    password = PasswordField("Password", validators=[Required()])
    remember_me = BooleanField('Keep me logged in')
    submit = SubmitField("Login")

app/forms/RegisterForm.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import Required, Email, EqualTo
from wtforms import ValidationError
from .. models.User import User 

class RegisterForm(FlaskForm):
    name = StringField("Name", validators=[Required()])
    email = StringField("Email", validators=[Required(), Email()])
    password = PasswordField("Password", validators=[Required(), 
                                EqualTo('confirm_password', 'Passwords must match!')])
    confirm_password = PasswordField("Confirm Password", validators=[Required()])
    submit = SubmitField("Login")


    def validate_email(self, field):
        if User.query.filter_by(email=field.data).first():
            raise ValidationError('Email already registered!')

app/forms/UpdateProfileForm.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed, FileField
from wtforms import StringField, SubmitField
from wtforms.validators import Required, Email

from wtforms import ValidationError
from .. models.User import User 
from flask_login import current_user

class UpdateProfileForm(FlaskForm):
    name = StringField("Name", validators=[Required()])
    email = StringField("Email", validators=[Required(), Email()])
    photo = FileField("Photo", validators=[FileAllowed(['jpg', 'png', 'gif'], 'Only Images are allowed!')])
    submit = SubmitField("Update")

    def validate_email(self, field):
        if field.data != current_user.email and User.query.filter_by(email=field.data).first():
            raise ValidationError('Email already registered!')

app/site/__init__.py
from flask import Blueprint

site = Blueprint('site', __name__)

from . import views, errors

app/site/views.py
import os
from flask import render_template, redirect, url_for, flash, request, current_app
from flask_login import login_user, logout_user, login_required, current_user
from werkzeug.utils import secure_filename
from .. forms.LoginForm import LoginForm
from .. forms.RegisterForm import RegisterForm
from .. forms.ChangePassword import ChangePassword
from .. forms.UpdateProfileForm import UpdateProfileForm
from .. forms.ForgotPasswordForm import ForgotPasswordForm
from . import site
from .. import db
from .. models.User import User
from ..emails import send_email

# from ..models import User

@site.route('/', methods=['GET', 'POST'])
def index():
    return render_template('site/index.html')

@site.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('site.index'))

    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user is not None and user.verify_password(form.password.data):
            login_user(user, form.remember_me.data)
            return redirect(request.args.get('next') or url_for('site.index'))
        flash('Invalid username or password', 'danger')

    return render_template('site/login.html', form=form)


@site.route("/logout")
@login_required
def logout():
    logout_user()
    flash('You have been logged out!', 'success')
    return redirect(url_for('site.index'))


@site.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('site.index'))

    form = RegisterForm()
    if form.validate_on_submit():
        user = User(name=form.name.data, email=form.email.data, 
                        password=form.password.data)
        db.session.add(user)
        flash('Successfully registered! You can now login.', 'success')
        return redirect(url_for('site.login'))
    return render_template('site/register.html', form=form)


@site.route('/change-password', methods=['GET', 'POST'])
@login_required
def changePassword():
    form = ChangePassword()
    if form.validate_on_submit():
        user = current_user
        if user is not None:
            user.password = form.password.data
            db.session.add(user)
            flash('Successfully changed the password', 'success')
            return redirect(url_for('site.index'))

    return render_template('site/change-password.html', form=form)


@site.route('/update-profile', methods=['GET', 'POST'])
@login_required
def updateProfile():
    user = current_user
    form = UpdateProfileForm(obj=user)

    if form.validate_on_submit():
        user.name = form.name.data
        user.email = form.email.data

        photo = request.files['photo']
        upload_folder = current_app.config['UPLOAD_FOLDER']
        if photo:
            filename = secure_filename(photo.filename)
            photo.save(os.path.join(upload_folder, filename))

        db.session.add(user)
        flash('Updated Profile!', 'success')
        return redirect(url_for('site.updateProfile'))
    return render_template('site/update-profile.html', form=form)


@site.route('/forgot-password', methods=['GET', 'POST'])
def forgotPassword():
    form = ForgotPasswordForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        token = user.generate_password_reset_token()
        # send_email(user.email, 'Confirm your account', 'site/emails/password-reset', user=user, token=token)
        flash('An email has been sent to you for further instructions.', 'success')
        return redirect(url_for('site.forgotPassword'))
    return render_template('site/forgot-password.html', form=form)

@site.route('/reset-password/<token>')
def resetPassword(token):
    user = User.load_user_by_token(token)
    return render_template('site/reset-password.html', user=user)
    

app/templates/site/change-password.html
{% extends "layouts/base.html" %}
{% block title %}Change Password{% endblock %}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}
    <div class="row">
        <div class="col-md-6">
            <h2>Change Password</h2>
            <div class="well">
                {{ wtf.quick_form(form) }}
            </div>
        </div>
    </div>
    
{% endblock %}

app/templates/site/forgot-password.html
{% extends "layouts/base.html" %} 
{% block title %}Forgot Password{% endblock %}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}

{% endblock %}
{% block content %}
<div class="row">
    <div class="col-md-12">
        <h2>Forgot Password</h2>
        <p>
            No worries, just fill in you email with which you registered in the form below and press submit.
            <br/>We will send you instructions on the same email address.
        </p>
    </div>
</div>
<div class="row">
    <div class="col-md-6">
        <div class="well">
            {{ wtf.quick_form(form) }}
        </div>
    </div>
</div>
{% endblock %}

app/templates/site/index.html
{% extends "layouts/base.html" %}
{% block title %}Index{% endblock %}

{% block breadcrumbs %}
    {% if current_user.is_authenticated %}
        <nav class="breadcrumb">
            <a class="breadcrumb-item" href="{{ url_for('site.index') }}">Home</a>
            <span class="breadcrumb-item active">Dashboard</span>
        </nav>
    {% endif %}
{% endblock %}

{% block content %}
{% if current_user.is_authenticated %}
    <h1 class="page-heading">Welcome {{ current_user.name }}!</h1>
    <br/><br/>
    <div class="panel panel-default">
        <div class="panel-heading">
            Batches
        </div>
        <div class="panel-body">
            <table class="table table-bordered table-responsive table-condensed">
                <thead>
                    <tr>
                        <th>S.no.</th>
                        <th>Date</th>
                        <th>Batch Name</th>
                        <th>Status</th>
                        <th>Action</th>
                    </tr>
                </thead>
                <tbody>
                    <tr>
                        <td>1</td>
                        <td>6 Dec, 2016</td>
                        <td>Banks Batch</td>
                        <td>
                            <i class="fa fa-2x fa-check-circle text-success v-a-middle"></i>
                            <span class="status">Completed</span>
                        </td>
                        <td>Details</td>
                    </tr>
                    <tr>
                        <td>1</td>
                        <td>6 Dec, 2016</td>
                        <td>Banks Batch</td>
                        <td>
                            <i class="fa fa-2x fa-spinner fa-spin v-a-middle" aria-hidden="true"></i>
                            <span class="status">In Progress</span>
                        </td>
                        <td>Details</td>
                    </tr>
                    <tr>
                        <td>1</td>
                        <td>6 Dec, 2016</td>
                        <td>Banks Batch</td>
                        <td>
                            <i class="fa fa-2x fa-times-circle text-danger v-a-middle"></i>
                            <span class="status">In Progress</span>
                        </td>
                        <td>Details</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>

{% else %}
    <h1 class="page-heading">Welcome to Rosetta SIP Generator!</h1>
{% endif %}
{% endblock %}

app/templates/site/login.html
{% extends "layouts/base.html" %}
{% block title %}Login{% endblock %}
{% block breadcrumbs %}
    <nav class="breadcrumb">
        <a class="breadcrumb-item" href="{{ url_for('site.index') }}">Home</a>
        <span class="breadcrumb-item active">Login</span>
    </nav>
{% endblock %}

{% import "bootstrap/wtf.html" as wtf %}
{% block content %}
    <div class="row">
        <div class="col-md-6">
            <h2>Login</h2>
            <div class="well">
                {{ wtf.quick_form(form) }}
                <br>
                <div class="row">
                    <div class="col-md-6"><a href="{{ url_for('site.forgotPassword') }}">Forgot Password?</a></div>
                    <div class="col-md-6">Not Registered yet, <a href="{{ url_for('site.register') }}">Register Here</a></div>
                </div>
            </div>
        </div>
    </div>
    
{% endblock %}

app/templates/site/register.html
{% extends "layouts/base.html" %} 
{% block title %}Register{% endblock %} 
{% import "bootstrap/wtf.html" as wtf %} 
{% block breadcrumbs %}
    <nav class="breadcrumb">
        <a class="breadcrumb-item" href="{{ url_for('site.index') }}">Home</a>
        <span class="breadcrumb-item active">Register</span>
    </nav>
{% endblock %}
{% block content %}
<div class="row">
    <div class="col-md-6">
        <h2>Register</h2>
        <div class="well">
            {{ wtf.quick_form(form) }}
            <br>
            <div class="row">
                <div class="col-md-6"></div>
                <div class="col-md-6">Already registered? <a href="{{ url_for('site.login') }}">Login Here</a></div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/site/reset-password.html
{% extends "layouts/base.html" %}
{% block title %}Reset Password{% endblock %}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}
    <div class="row">
        <div class="col-md-6">
            <h2>Reset Password</h2>
            {{ user.name }}
        </div>
    </div>
{% endblock %}

app/templates/site/update-profile.html
{% extends "layouts/base.html" %}
{% block title %}Update Profile{% endblock %}
{% import "bootstrap/wtf.html" as wtf %}
{% block content %}
    <div class="row">
        <div class="col-md-6">
            <h2>Update Profile</h2>
            <div class="well">
                {{ wtf.quick_form(form, enctype="multipart/form-data") }}
            </div>
        </div>
    </div>
{% endblock %}